version: '3.7'

services:
  db:
    image: postgres:12.3
    volumes:
      - postgres:/var/lib/postgresql/data
    env_file: .env
    ports:
      - "5432:5432"

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  app:
    build: .
    depends_on:
      - db
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    env_file: .env
#    command: bash -c "rm -f tmp/pids/server.pid && sleep 100000"
    command: docker-entrypoint.sh
    stdin_open: true
    tty: true

volumes:
  postgres: