version: '3.7'

services:
  db:
    image: postgres:12.3
    volumes:
      - postgres:/var/lib/postgresql/data
    env_file: .env
    ports:
      - "5432:5432"

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

volumes:
  postgres: