default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  host: <%= ENV['POSTGRES_HOST'] %>
  template: template0

development:
  <<: *default
  database: mystocks_development

test:
  <<: *default
  database: mystocks_test

production:
  <<: *default
  database: mystocks_production
  password: <%= ENV["MYSTOCKS_DATABASE_PASSWORD"] %>
